[package]
name = "struct-table"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true

[target.'cfg(target_arch = "bpf")'.dependencies]
solana-compiler-builtins = { git = "https://github.com/blueshift-gg/solana-compiler-builtins", version = "0.1.0" }

[dev-dependencies]
harness = { workspace = true }
